# Generated by Django 4.2.24 on 2025-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_module_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='module_videos/'),
        ),
    ]
