# Generated by Django 4.2.24 on 2025-10-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_module_video'),
        ('contest', '0006_alter_contest_difficulty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedKeynote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('generated_by', models.CharField(default='gemini', max_length=100)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keynotes', to='contest.contest')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_keynotes', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
