# Generated by Django 4.2.20 on 2025-10-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0007_summarizedkeynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizedkeynote',
            options={'verbose_name': 'Summarized Key Note', 'verbose_name_plural': 'Summarized Key Notes'},
        ),
        migrations.RemoveField(
            model_name='summarizedkeynote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='summarizedkeynote',
            name='course',
        ),
        migrations.AddField(
            model_name='summarizedkeynote',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='summarizedkeynote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='contest.question'),
        ),
        migrations.AddField(
            model_name='summarizedkeynote',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarizedkeynote',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='summarizedkeynote',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
