# Generated by Django 4.2.20 on 2025-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_alter_summarizedkeynote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ai_summary_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
