# Generated by Django 4.2.20 on 2025-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_emaillog_contest_auto_email_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
