# Generated by Django 4.2.24 on 2025-10-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_tutorapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorApplication',
        ),
    ]
