# Generated by Django 4.2.24 on 2025-10-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_delete_tutorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorvideo',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='education',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user_profile.tutor'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user_profile.tutor'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_profile.tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='TutorVideo',
        ),
    ]
